stages:
  - compile
  - test

compile-tests:
  stage: compile
  tags:
    - gcc
  script:
    - which gcc
    - gcc --version
    - which cmake
    - cmake --version
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ../cmake
    - cmake --build .
  artifacts:
    paths:
      - build/lmp


test-md-energy-conservation:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run
    - ../../build/lmp -in in.md.forces
    - python analyse_energy_convergence.py log.lammps